backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"

local_backend: true

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "_data/content.json"
        fields:
          - { label: "Wat is HAT", name: "what_is_hat", widget: "markdown" }
          - { label: "De oorsprong van HAT", name: "origin", widget: "markdown" }
          - { label: "10 redenenen", name: "reasons", widget: "markdown" }
          - { label: "Doel", name: "goals", widget: "markdown" }
          - { label: "Praktisch", name: "practical", widget: "markdown" }
          - { label: "Betaling", name: "payment", widget: "markdown" }
          - { label: "Annulatie", name: "cancelation", widget: "markdown" }
          - { label: "Inschrijvingsformulier", name: "signup", widget: "markdown" }
